### ISSUE TITLE
[BUG REPORT] post_max_size/upload_max_filesize = 0 doesnt work

### ISSUE THREAD

**Issue by chdietrich** [aarpon/hrm#4] opened 2019-04-30 12:32 UTC
**Describe the bug**
Setting post_max_size and upload_max_filesize in php.ini to 0 (unlimited) breaks file upload.

**To Reproduce**
Set the following in php.ini:
post_max_size = 0
upload_max_filesize = 0

**Expected behavior**
HRM system summary should display the correct values (unlimited instead of "0"/"limited by php.ini") and the file upload should still work.

**Environment**
***Server-side***
CentOS Linux release 7.6.1810
PHP 7.2.10
Apache/2.4.6
PostgreSQL 9.2.24
HRM 3.6.0

***Client-side***
Firefox 66.0.3 / Chrome 74.0.3729.108

**Additional context**
Problem probably located in "inc/FileBrowser.php" at Line 49.

**Comment by KevinNamink** [comment] 2024-01-12 11:37
There has been a fix for the parsing of file sizes, I recall that the Mb or Gb suffix caused issues with parsing in some situations. I cannot find the commit anymore. Perhaps this issue was related.

Either way this issue is now very old and I cannot reproduce it. I'm closing this issue, it can be opened again if this is still a problem.

**Closed by KevinNamink** 2024-01-12 11:37 UTC
Labels: bug
